# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftictactoe.proto\"\x0c\n\nAckRequest\"\'\n\x0b\x41\x63kResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"\r\n\x0bTimeRequest\"\x1c\n\x0cTimeResponse\x12\x0c\n\x04time\x18\x01 \x01(\t\"\x1c\n\x07SetTime\x12\x11\n\ttime_diff\x18\x01 \x01(\x02\"\x1d\n\rSetTimeString\x12\x0c\n\x04time\x18\x01 \x01(\t\"(\n\x0fSetTimeResponse\x12\x15\n\rtime_accepted\x18\x01 \x01(\x08\"\x1d\n\x0f\x45lectionMessage\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x10\x45lectionResponse\x12\x17\n\x0f\x61\x63knowledgement\x18\x01 \x01(\x08\",\n\x12\x43oordinatorMessage\x12\x16\n\x0e\x63oordinator_id\x18\x01 \x01(\x05\"\x1b\n\x0bMoveRequest\x12\x0c\n\x04tile\x18\x01 \x01(\x05\"\x1f\n\x0cMoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xcf\x02\n\tTicTacToe\x12\"\n\x03\x41\x63k\x12\x0b.AckRequest\x1a\x0c.AckResponse\"\x00\x12%\n\x04Time\x12\x0c.TimeRequest\x1a\r.TimeResponse\"\x00\x12+\n\x0bReceiveTime\x12\x08.SetTime\x1a\x10.SetTimeResponse\"\x00\x12\x37\n\x11ReceiveTimeString\x12\x0e.SetTimeString\x1a\x10.SetTimeResponse\"\x00\x12%\n\x04Move\x12\x0c.MoveRequest\x1a\r.MoveResponse\"\x00\x12\x31\n\x08\x45lection\x12\x10.ElectionMessage\x1a\x11.ElectionResponse\"\x00\x12\x37\n\x0b\x43oordinator\x12\x13.CoordinatorMessage\x1a\x11.ElectionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tictactoe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACKREQUEST._serialized_start=19
  _ACKREQUEST._serialized_end=31
  _ACKRESPONSE._serialized_start=33
  _ACKRESPONSE._serialized_end=72
  _TIMEREQUEST._serialized_start=74
  _TIMEREQUEST._serialized_end=87
  _TIMERESPONSE._serialized_start=89
  _TIMERESPONSE._serialized_end=117
  _SETTIME._serialized_start=119
  _SETTIME._serialized_end=147
  _SETTIMESTRING._serialized_start=149
  _SETTIMESTRING._serialized_end=178
  _SETTIMERESPONSE._serialized_start=180
  _SETTIMERESPONSE._serialized_end=220
  _ELECTIONMESSAGE._serialized_start=222
  _ELECTIONMESSAGE._serialized_end=251
  _ELECTIONRESPONSE._serialized_start=253
  _ELECTIONRESPONSE._serialized_end=296
  _COORDINATORMESSAGE._serialized_start=298
  _COORDINATORMESSAGE._serialized_end=342
  _MOVEREQUEST._serialized_start=344
  _MOVEREQUEST._serialized_end=371
  _MOVERESPONSE._serialized_start=373
  _MOVERESPONSE._serialized_end=404
  _EMPTY._serialized_start=406
  _EMPTY._serialized_end=413
  _TICTACTOE._serialized_start=416
  _TICTACTOE._serialized_end=751
# @@protoc_insertion_point(module_scope)
